export let gastosSimulados=Array(
     {
          id:1,
          descripcion:"Pasajes Buenos Aires",
          monto:8000,
          fecha:"2024-9-20",
          categoria:"transporte"
     },
     {
          id:2,
          descripcion:"Hamburguesa + coca cola",
          monto:21000,
          fecha:"2024-9-20",
          categoria:"comida"
     },
     {
          id:3,
          descripcion:"Servicio públicos e impuestos",
          monto:247000,
          fecha:"2024-9-22",
          categoria:"Impuestos"
     },
     {
          id:4,
          descripcion:"Servicio Hogar",
          monto:86247,
          fecha:"2024-9-22",
          categoria:"Telecomunicaciones" 
     },
     {
          id:5,
          descripcion:"Tarjeta de credito",
          monto:136000,
          fecha:"2024-9-18", 
          categoria:"Bancarios" 
     },    
     {
          id:6,
          descripcion:"Alimentos",
          monto:800000,
          fecha:"2024-9-15", 
          categoria:"Mercado"

     },
     {
          id:7,
          descripcion:"Ropa",
          monto:350000,
          fecha:"2024-9-19", 
          categoria:"Vestuario" 
     },
     {
          id:8,
          descripcion:"Diversion",
          monto:185000,
          fecha:"2024-9-21",
          categoria:"Entretenimiento"  
     },
     {
          id:9,
          descripcion:"Administración",
          monto:174650,
          fecha:"2024-8-30",
          categoria:"Edificio"
     },
     {
          id:10,
          descripcion:"Pasajes",
          monto:162000,
          fecha:"2024-9-15",
          categoria:"transporte"
     },                                       
     {
          id:11,
          descripcion:"Gastos varios",
          monto:36000,
          fecha:"2024-9-19",
          categoria:"Otros" 
     },
     {
          id:12,
          descripcion:"Plan postpago",
          monto:17450,
          fecha:"2024-8-30", 
          categoria:"moviles"
     },
     {
          id:13,
          descripcion:"motos",
          monto:40000,
          fecha:"2024-9-17",
          categoria:"Parqueadero" 
     },
     {
          id:14,
          descripcion:"Impresión",
          monto:13000,
          fecha:"2024-9-19",
          categoria:"Papeleria" 
     },
     {
          id:15,
          descripcion:"Creditos almacenes",
          monto:125000,
          fecha:"2024-9-15",
          categoria:"Creditospropios" 
     },
     {
          id:16,
          descripcion:"Microfono",
          monto:350000,
          fecha:"2024-8-15",
          categoria:"Tecnologia" 
     },
     {
          id:17,
          descripcion:"Medicamentos",
          monto:18000,
          fecha:"2024-9-19", 
          categoria:"Farmacia" 
     },
     {
          id:18,
          descripcion:"Cuota EPS",
          monto:4550,
          fecha:"2024-8-10",
          categoria:"EPS" 
     },
     {
          id:19,
          descripcion:"Semiacidas",
          monto:5500,
          fecha:"2024-8-01",
          categoria:"Frutas" 
     },
     {
          id:20,
          descripcion:"Cuota manejo tarjeta",
          monto:4100,
          fecha:"2024-8-30",
          categoria:"Bancarios"  
     }
)

